version: '2.1'

services:
  dockerized:
    image: dockerized
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 8080:8080
      - 9229:9229
    volumes:
      - .:/usr/src/app
    command: node --inspect server.js